"""
DLL Autograd C++ extension
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Tensor', 'cat', 'gpu_available', 'gpu_device_name', 'rand', 'randn', 'seed', 'stack']
class Tensor:
    requires_grad: bool
    @typing.overload
    def __add__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __getitem__(self, arg0: typing.Any) -> Tensor:
        ...
    @typing.overload
    def __init__(self, data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self, data: list) -> None:
        ...
    def __matmul__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __mul__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __pow__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __pow__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __radd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rpow__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rsub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rtruediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __sub__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __truediv__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def abs(self) -> Tensor:
        ...
    def backward(self, grad: Tensor = None) -> None:
        ...
    def cbrt(self) -> Tensor:
        ...
    def cholesky(self) -> Tensor:
        ...
    def cholesky_solve(self, l: Tensor) -> Tensor:
        ...
    def cos(self) -> Tensor:
        ...
    def cpu(self) -> Tensor:
        ...
    def det(self) -> Tensor:
        ...
    def diag(self, diagonal: typing.SupportsInt | typing.SupportsIndex = 0) -> Tensor:
        ...
    def eig(self) -> tuple[Tensor, Tensor]:
        ...
    def exp(self) -> Tensor:
        ...
    def inv(self) -> Tensor:
        ...
    def is_gpu(self) -> bool:
        ...
    def item(self) -> float:
        ...
    def log(self) -> Tensor:
        ...
    def lstsq(self, b: Tensor) -> Tensor:
        ...
    def lu(self) -> tuple[Tensor, Tensor, Tensor]:
        ...
    def lu_factor(self) -> tuple[Tensor, Tensor]:
        ...
    def lu_solve(self, lu: Tensor, pivots: Tensor, adjoint: bool = False) -> Tensor:
        ...
    def matrix_exp(self) -> Tensor:
        ...
    @typing.overload
    def max(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def max(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def mean(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def mean(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def min(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def min(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def prod(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def prod(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    def qr(self) -> tuple[Tensor, Tensor]:
        ...
    def relu(self) -> Tensor:
        ...
    def reshape(self, shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    def sigmoid(self) -> Tensor:
        ...
    def sin(self) -> Tensor:
        ...
    def softmax(self, dim: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
        ...
    def solve(self, b: Tensor) -> Tensor:
        ...
    def sqrt(self) -> Tensor:
        ...
    def squeeze(self, dim: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
        ...
    @typing.overload
    def std(self, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    @typing.overload
    def std(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    @typing.overload
    def sum(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def sum(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    def svd(self, full_matrices: bool = True) -> tuple[Tensor, Tensor, Tensor]:
        ...
    def tanh(self) -> Tensor:
        ...
    def to(self, device: str) -> Tensor:
        ...
    def transpose(self, dim0: typing.SupportsInt | typing.SupportsIndex = -2, dim1: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
        ...
    def unsqueeze(self, dim: typing.SupportsInt | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def var(self, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    @typing.overload
    def var(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    def zero_grad(self) -> None:
        ...
    @property
    def data(self) -> list[float]:
        ...
    @property
    def device(self) -> str:
        ...
    @property
    def grad(self) -> Tensor:
        ...
    @property
    def shape(self) -> list[int]:
        ...
def cat(tensors: collections.abc.Sequence[Tensor], dim: typing.SupportsInt | typing.SupportsIndex = 0) -> Tensor:
    ...
def gpu_available() -> bool:
    ...
def gpu_device_name() -> str:
    ...
def rand(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], min: typing.SupportsFloat | typing.SupportsIndex = 0, max: typing.SupportsFloat | typing.SupportsIndex = 1) -> Tensor:
    ...
def randn(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], mu: typing.SupportsFloat | typing.SupportsIndex = 0, std: typing.SupportsFloat | typing.SupportsIndex = 1) -> Tensor:
    ...
def seed(seed: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def stack(tensors: collections.abc.Sequence[Tensor], dim: typing.SupportsInt | typing.SupportsIndex = 0) -> Tensor:
    ...
