from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Tensor', 'rand', 'randn']
class Tensor:
    requires_grad: bool
    @typing.overload
    def __add__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __getitem__(self, arg0: typing.Any) -> Tensor:
        ...
    def __init__(self, data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def __matmul__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __mul__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __pow__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __pow__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __radd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rpow__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rsub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def __rtruediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __sub__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    @typing.overload
    def __truediv__(self, arg0: Tensor) -> Tensor:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
        ...
    def abs(self) -> Tensor:
        ...
    def backward(self) -> None:
        ...
    def cbrt(self) -> Tensor:
        ...
    def cos(self) -> Tensor:
        ...
    def exp(self) -> Tensor:
        ...
    def item(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> float:
        ...
    def log(self) -> Tensor:
        ...
    @typing.overload
    def max(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def max(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def mean(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def mean(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def min(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def min(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def prod(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def prod(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    def relu(self) -> Tensor:
        ...
    def sigmoid(self) -> Tensor:
        ...
    def sin(self) -> Tensor:
        ...
    def softmax(self, dim: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
        ...
    def sqrt(self) -> Tensor:
        ...
    @typing.overload
    def std(self, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    @typing.overload
    def std(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    @typing.overload
    def sum(self, keepdim: bool = False) -> Tensor:
        ...
    @typing.overload
    def sum(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False) -> Tensor:
        ...
    def tanh(self) -> Tensor:
        ...
    def transpose(self, dim0: typing.SupportsInt | typing.SupportsIndex = -2, dim1: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
        ...
    @typing.overload
    def var(self, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    @typing.overload
    def var(self, dim: typing.SupportsInt | typing.SupportsIndex, keepdim: bool = False, unbiased: bool = True) -> Tensor:
        ...
    def zero_grad(self) -> None:
        ...
    @property
    def data(self) -> list[float]:
        ...
    @property
    def grad(self) -> Tensor:
        ...
    @property
    def shape(self) -> list[int]:
        ...
    @property
    def strides(self) -> list[int]:
        ...
def rand(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], min: typing.SupportsFloat | typing.SupportsIndex = 0, max: typing.SupportsFloat | typing.SupportsIndex = 1) -> Tensor:
    ...
def randn(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], mu: typing.SupportsFloat | typing.SupportsIndex = 0, std: typing.SupportsFloat | typing.SupportsIndex = 1) -> Tensor:
    ...
